openapi: 3.0.1
info:
  title: Public Variable Definitions API
  description: Public Variable Definitions
  contact:
    name: Team Metadata
    email: metadata@ssb.no
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/deed.no
  version: "0.1"
servers:
- url: https://metadata.ssb.no
  description: Public server
- url: https://metadata.test.ssb.no
  description: Public test server
- url: http://localhost:8080
  description: Local development
security: []
tags:
- name: Variable Definitions
  description: Read Public Variable Definitions.
- name: Validity Periods
  description: Read Validity Periods for Public Variable Definitions.
paths:
  /public/variable-definitions:
    get:
      tags:
      - Variable Definitions
      summary: List all variable definitions.
      description: "List all variable definitions. These are rendered in the given\
        \ language, with the default being Norwegian Bokmål."
      operationId: listPublicVariableDefinitions
      parameters:
      - name: Accept-Language
        in: header
        description: Render the variable definition in the given language.
        allowEmptyValue: true
        schema:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/SupportedLanguages"
        examples:
          Date not specified:
            value: nb
      - name: date_of_validity
        in: query
        description: List only variable definitions which are valid on this date.
        explode: false
        schema:
          type: string
          format: date
          nullable: true
        examples:
          Specific date:
            value: 1970-01-01
      responses:
        "200":
          description: OK response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RenderedView"
              examples:
                Specific date:
                  value: |-
                    [
                        {
                        "id": "wypvb3wd",
                        "name": "Landbakgrunn",
                        "short_name": "string",
                        "definition": "For personer født i utlandet, er dette (med noen få unntak) eget fødeland. For personer født i Norge er det foreldrenes fødeland. I de tilfeller der foreldrene har ulikt fødeland, er det morens fødeland som blir valgt. Hvis ikke personen selv eller noen av foreldrene er utenlandsfødt, hentes landbakgrunn fra de første utenlandsfødte en treffer på i rekkefølgen mormor, morfar, farmor eller farfar.",
                        "classification_uri": "https://www.ssb.no/en/klass/klassifikasjoner/91",
                        "unit_types": [{
                                "reference_uri": "https://www.ssb.no/klass/klassifikasjoner/702",
                                "code": "20",
                                "title": "Person"
                            }
                        ],
                        "subject_fields": [
                        {
                                "reference_uri": "https://www.ssb.no/klass/klassifikasjoner/618",
                                "code": "be07",
                                "title": "Innvandrere"
                            }
                        ],
                        "contains_special_categories_of_personal_data": true,
                        "variable_status": "PUBLISHED_INTERNAL",
                        "measurement_type": null,
                        "valid_from": "2003-01-01",
                        "valid_until": null,
                        "external_reference_uri": "https://www.ssb.no/a/metadata/conceptvariable/vardok/1919/nb",
                        "comment": "Fra og med 1.1.2003 ble definisjon endret til også å trekke inn besteforeldrenes fødeland.",
                        "related_variable_definition_uris": [
                            "https://example.com/"
                        ],
                        "owner": {
                            "team": "team-a",
                            "groups": ["team-a-developers"]
                        },
                        "contact": {
                            "title": "Seksjon for befolkningsstatistikk",
                            "email": "s320@ssb.no"
                        },
                        "created_at": "2024-06-11T08:15:19.038Z",
                        "created_by": "ano@ssb.no",
                        "last_updated_at": "2024-06-11T08:15:19.038Z",
                        "last_updated_by": "ano@ssb.no"
                    }
                    ]
                Date not specified:
                  value: "[]"
  /public/variable-definitions/{variable-definition-id}:
    get:
      tags:
      - Variable Definitions
      summary: Get one variable definition.
      description: "Get one variable definition. This is rendered in the given language,\
        \ with the default being Norwegian Bokmål."
      operationId: getPublicVariableDefinitionById
      parameters:
      - name: variable-definition-id
        in: path
        description: Unique identifier for the variable definition.
        required: true
        schema:
          type: string
        examples:
          Date not specified:
            value: wypvb3wd
          Specific date:
            value: wypvb3wd
          Not found:
            value: invalid id
      - name: Accept-Language
        in: header
        description: Render the variable definition in the given language.
        allowEmptyValue: true
        schema:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/SupportedLanguages"
        examples:
          Date not specified:
            value: nb
          Specific date:
            value: nb
      - name: date_of_validity
        in: query
        description: List only variable definitions which are valid on this date.
        explode: false
        schema:
          type: string
          format: date
          nullable: true
        examples:
          Specific date:
            value: 1970-01-01
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RenderedView"
              examples:
                Date not specified:
                  value:
                    id: wypvb3wd
                    name: Landbakgrunn
                    short_name: string
                    definition: "For personer født i utlandet, er dette (med noen\
                      \ få unntak) eget fødeland. For personer født i Norge er det\
                      \ foreldrenes fødeland. I de tilfeller der foreldrene har ulikt\
                      \ fødeland, er det morens fødeland som blir valgt. Hvis ikke\
                      \ personen selv eller noen av foreldrene er utenlandsfødt, hentes\
                      \ landbakgrunn fra de første utenlandsfødte en treffer på i\
                      \ rekkefølgen mormor, morfar, farmor eller farfar."
                    classification_uri: https://www.ssb.no/en/klass/klassifikasjoner/91
                    unit_types:
                    - reference_uri: https://www.ssb.no/klass/klassifikasjoner/702
                      code: "20"
                      title: Person
                    subject_fields:
                    - reference_uri: https://www.ssb.no/klass/klassifikasjoner/618
                      code: be07
                      title: Innvandrere
                    contains_special_categories_of_personal_data: true
                    variable_status: PUBLISHED_INTERNAL
                    valid_from: 2003-01-01
                    external_reference_uri: https://www.ssb.no/a/metadata/conceptvariable/vardok/1919/nb
                    comment: Fra og med 1.1.2003 ble definisjon endret til også å
                      trekke inn besteforeldrenes fødeland.
                    related_variable_definition_uris:
                    - https://example.com/
                    owner:
                      team: team-a
                      groups:
                      - team-a-developers
                    contact:
                      title: Seksjon for befolkningsstatistikk
                      email: s320@ssb.no
                    created_at: 2024-06-11T08:15:19.038Z
                    created_by: ano@ssb.no
                    last_updated_at: 2024-06-11T08:15:19.038Z
                    last_updated_by: ano@ssb.no
                Specific date:
                  value:
                    id: wypvb3wd
                    name: Landbakgrunn
                    short_name: string
                    definition: "For personer født i utlandet, er dette (med noen\
                      \ få unntak) eget fødeland. For personer født i Norge er det\
                      \ foreldrenes fødeland. I de tilfeller der foreldrene har ulikt\
                      \ fødeland, er det morens fødeland som blir valgt. Hvis ikke\
                      \ personen selv eller noen av foreldrene er utenlandsfødt, hentes\
                      \ landbakgrunn fra de første utenlandsfødte en treffer på i\
                      \ rekkefølgen mormor, morfar, farmor eller farfar."
                    classification_uri: https://www.ssb.no/en/klass/klassifikasjoner/91
                    unit_types:
                    - reference_uri: https://www.ssb.no/klass/klassifikasjoner/702
                      code: "20"
                      title: Person
                    subject_fields:
                    - reference_uri: https://www.ssb.no/klass/klassifikasjoner/618
                      code: be07
                      title: Innvandrere
                    contains_special_categories_of_personal_data: true
                    variable_status: PUBLISHED_INTERNAL
                    valid_from: 2003-01-01
                    external_reference_uri: https://www.ssb.no/a/metadata/conceptvariable/vardok/1919/nb
                    comment: Fra og med 1.1.2003 ble definisjon endret til også å
                      trekke inn besteforeldrenes fødeland.
                    related_variable_definition_uris:
                    - https://example.com/
                    owner:
                      team: team-a
                      groups:
                      - team-a-developers
                    contact:
                      title: Seksjon for befolkningsstatistikk
                      email: s320@ssb.no
                    created_at: 2024-06-11T08:15:19.038Z
                    created_by: ano@ssb.no
                    last_updated_at: 2024-06-11T08:15:19.038Z
                    last_updated_by: ano@ssb.no
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.1.yaml#/Problem
              examples:
                Not found:
                  value:
                    type: about:blank
                    status: 404
                    detail: Not found
                    parameters: {}
  /public/variable-definitions/{variable-definition-id}/validity-periods:
    get:
      tags:
      - Validity Periods
      summary: List all validity periods.
      description: "List all validity periods. These are rendered in the given language,\
        \ with the default being Norwegian Bokmål."
      operationId: listPublicValidityPeriods
      parameters:
      - name: variable-definition-id
        in: path
        description: Unique identifier for the variable definition.
        required: true
        schema:
          type: string
        examples:
          Validity periods:
            value: wypvb3wd
          Not found:
            value: invalid id
      - name: Accept-Language
        in: header
        description: Render the variable definition in the given language.
        allowEmptyValue: true
        schema:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/SupportedLanguages"
        examples:
          Validity periods:
            value: nb
          Not found:
            value: nb
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RenderedView"
              examples:
                Validity periods:
                  value: |-
                    [
                        {
                        "id": "wypvb3wd",
                        "name": "Landbakgrunn",
                        "short_name": "string",
                        "definition": "For personer født i utlandet, er dette (med noen få unntak) eget fødeland. For personer født i Norge er det foreldrenes fødeland. I de tilfeller der foreldrene har ulikt fødeland, er det morens fødeland som blir valgt. Hvis ikke personen selv eller noen av foreldrene er utenlandsfødt, hentes landbakgrunn fra de første utenlandsfødte en treffer på i rekkefølgen mormor, morfar, farmor eller farfar.",
                        "classification_uri": "https://www.ssb.no/en/klass/klassifikasjoner/91",
                        "unit_types": [{
                                "reference_uri": "https://www.ssb.no/klass/klassifikasjoner/702",
                                "code": "20",
                                "title": "Person"
                            }
                        ],
                        "subject_fields": [
                        {
                                "reference_uri": "https://www.ssb.no/klass/klassifikasjoner/618",
                                "code": "be07",
                                "title": "Innvandrere"
                            }
                        ],
                        "contains_special_categories_of_personal_data": true,
                        "variable_status": "PUBLISHED_INTERNAL",
                        "measurement_type": null,
                        "valid_from": "2003-01-01",
                        "valid_until": null,
                        "external_reference_uri": "https://www.ssb.no/a/metadata/conceptvariable/vardok/1919/nb",
                        "comment": "Fra og med 1.1.2003 ble definisjon endret til også å trekke inn besteforeldrenes fødeland.",
                        "related_variable_definition_uris": [
                            "https://example.com/"
                        ],
                        "owner": {
                            "team": "team-a",
                            "groups": ["team-a-developers"]
                        },
                        "contact": {
                            "title": "Seksjon for befolkningsstatistikk",
                            "email": "s320@ssb.no"
                        },
                        "created_at": "2024-06-11T08:15:19.038Z",
                        "created_by": "ano@ssb.no",
                        "last_updated_at": "2024-06-11T08:15:19.038Z",
                        "last_updated_by": "ano@ssb.no"
                    }
                    ]
components:
  schemas:
    KlassReference:
      required:
      - reference_uri
      type: object
      properties:
        reference_uri:
          type: string
        code:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
    Owner:
      required:
      - groups
      - team
      type: object
      properties:
        team:
          minLength: 1
          type: string
          description: The Dapla team with responsibility for this variable definition.
        groups:
          minItems: 1
          type: array
          description: The groups with permission to modify this variable definition.
          items:
            minLength: 1
            type: string
      description: "Owner of the definition, i.e. responsible Dapla team (statistics\
        \ team) and information about access management groups."
      example:
        team: play-obr-b
        groups:
        - play-obr-b-developers
    RenderedContact:
      required:
      - email
      - title
      type: object
      properties:
        title:
          type: string
        email:
          type: string
      example:
        title: Seksjon for befolkningsstatistikk
        email: s320@ssb.no
    RenderedView:
      required:
      - contains_special_categories_of_personal_data
      - created_at
      - created_by
      - id
      - last_updated_at
      - last_updated_by
      - owner
      - patch_id
      - short_name
      - subject_fields
      - unit_types
      - valid_from
      - variable_status
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the variable definition.
          format: "^[a-zA-Z0-9-_]{8}$"
        patch_id:
          type: integer
          description: Integer identifying a patch of a variable definition.
          format: int32
          example: 1
        name:
          type: string
          description: Name of the variable. Must be unique for a given Unit Type
            and Owner combination.
          nullable: true
        short_name:
          type: string
          description: Recommended short name. Must be unique within an organization.
        definition:
          type: string
          description: Definition of the variable.
          nullable: true
        classification_uri:
          type: string
          description: Link to the classification which defines all permitted values
            for this variable.
          nullable: true
        unit_types:
          type: array
          items:
            $ref: "#/components/schemas/KlassReference"
        subject_fields:
          type: array
          items:
            $ref: "#/components/schemas/KlassReference"
        contains_special_categories_of_personal_data:
          type: boolean
          description: "True if variable instances contain particularly sensitive\
            \ information. Applies even if the information or identifiers are pseudonymized.\
            \ Information within the following categories are regarded as particularly\
            \ sensitive: Ethnicity, Political alignment, Religion, Philosophical beliefs,\
            \ Union membership, Genetics, Biometrics, Health, Sexual relations, Sexual\
            \ orientation"
        variable_status:
          $ref: "#/components/schemas/VariableStatus"
        measurement_type:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/KlassReference"
        valid_from:
          type: string
          description: The variable definition is valid from this date inclusive
          format: date
        valid_until:
          type: string
          description: The variable definition is valid until this date inclusive
          format: date
          nullable: true
        external_reference_uri:
          type: string
          description: A link (URI) to an external definition/documentation
          format: url
          nullable: true
        comment:
          type: string
          description: Optional comment to explain the definition or communicate potential
            changes.
          nullable: true
        related_variable_definition_uris:
          type: array
          description: "Link(s) to related definitions of variables - a list of one\
            \ or more definitions. For example for a variable after-tax income it\
            \ could be relevant to link to definitions of income from work, property\
            \ income etc."
          nullable: true
          items:
            type: string
            format: url
        owner:
          $ref: "#/components/schemas/Owner"
        contact:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/RenderedContact"
        created_at:
          type: string
          description: The timestamp at which this variable definition was first created.
          format: date-time
        created_by:
          type: string
          description: The user who created this variable definition.
        last_updated_at:
          type: string
          description: The timestamp at which this variable definition was last modified.
          format: date-time
        last_updated_by:
          type: string
          description: The user who last modified this variable definition.
      description: "Render a Variable Definition in a specific language, for display\
        \ to end users."
      example:
        id: wypvb3wd
        name: Landbakgrunn
        short_name: string
        definition: "For personer født i utlandet, er dette (med noen få unntak) eget\
          \ fødeland. For personer født i Norge er det foreldrenes fødeland. I de\
          \ tilfeller der foreldrene har ulikt fødeland, er det morens fødeland som\
          \ blir valgt. Hvis ikke personen selv eller noen av foreldrene er utenlandsfø\
          dt, hentes landbakgrunn fra de første utenlandsfødte en treffer på i rekkefø\
          lgen mormor, morfar, farmor eller farfar."
        classification_uri: https://www.ssb.no/en/klass/klassifikasjoner/91
        unit_types:
        - reference_uri: https://www.ssb.no/klass/klassifikasjoner/702
          code: "20"
          title: Person
        subject_fields:
        - reference_uri: https://www.ssb.no/klass/klassifikasjoner/618
          code: be07
          title: Innvandrere
        contains_special_categories_of_personal_data: true
        variable_status: PUBLISHED_INTERNAL
        measurement_type: null
        valid_from: 2003-01-01
        valid_until: null
        external_reference_uri: https://www.ssb.no/a/metadata/conceptvariable/vardok/1919/nb
        comment: Fra og med 1.1.2003 ble definisjon endret til også å trekke inn besteforeldrenes
          fødeland.
        related_variable_definition_uris:
        - https://example.com/
        owner:
          team: team-a
          groups:
          - team-a-developers
        contact:
          title: Seksjon for befolkningsstatistikk
          email: s320@ssb.no
        created_at: 2024-06-11T08:15:19.038Z
        created_by: ano@ssb.no
        last_updated_at: 2024-06-11T08:15:19.038Z
        last_updated_by: ano@ssb.no
    SupportedLanguages:
      type: string
      description: Languages the application supports.
      enum:
      - nb
      - nn
      - en
      x-enum-descriptions:
      - Norwegian Bokmål
      - Norwegian Nynorsk
      - English
    VariableStatus:
      type: string
      description: Status of the life cycle of the variable
      enum:
      - DRAFT
      - PUBLISHED_INTERNAL
      - PUBLISHED_EXTERNAL
